name: orange-bovine
favicon: null
layout_spectrum: 0.4057815333362669
typography_spectrum: 0.24920610710978508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.030489641474559903
  lightness: 0.7502688686363399
  saturation: 0.18535050633363426
  rhythmicContrast: 0.040058437967672944
purpose: []
